# Generated by Django 3.1.3 on 2022-05-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_aythor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='aythor',
            new_name='author',
        ),
    ]
